name = "hono-starter-cloudflare-test"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true


[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
LOG_LEVEL = "info"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "hono-template"
database_id = "d39d22da-cd9b-4274-9794-2070db226ed5"
migrations_dir = "src/db/migrations"

[env.local]

[env.local.vars]
LOG_LEVEL = "debug"

[[env.local.d1_databases]]
binding = "DB"
database_name = "hono-template"
database_id = "d39d22da-cd9b-4274-9794-2070db226ed5"
migrations_dir = "src/db/migrations"
